### ISSUE TITLE
Is it possible to add the serverless dependencies to root level?

### ISSUE THREAD

**Issue by walterholohan** [antoinewg/turbo-serverless-typescript-starter#2]
A benefit of using a mono-repo is dependency management. Just wondering is it possible to add the serverless dependencies to the root level so that you don't have to add them to each service's `package.json`

**Comment by antoinewg** [comment]
Yes it's possible, I have most dependencies in api services right now, because I duplicated the first one, but to have the same serverless version across services, you can have it at the root package.json 👍

**Comment by walterholohan** [comment]
Fantastic, thanks for the quick reply

**Comment by walterholohan** [comment]
@antoinewg were you able to get the cache working? Im using serverless-esbuild to build the serverless package but turbo is always returning a miss for the cache.

Also, one other thing that I would like to achieve is conditional deployments. I only want to do a `sls deploy` if something has changed in the service. Did you manage to achieve this?

**Comment by antoinewg** [comment]
Hey @walterholohan . Sorry for the delay, but I think I got it working.

You can check the `deployment` section in the readme, but basically, you can run `pnpm deploy:staging` with `AWS_PROFILE` variable set, and it should deploy once.

If you make a change to a function, it will only deploy the changed endpoints:

![image](https://user-images.githubusercontent.com/10118284/224710011-40d7d132-5c67-4674-a5ea-6238e66a4ffe.png)

As you can see, after making changes to `api2`, I have `Deploying api2 to stage staging (eu-central-1)`
and for `api1`, which didn't change: `No changes to deploy. Deployment skipped. (0s)`

If you then make change to the helpers pacakge. Both functions will be redeployed.

Please let me know if this works for you.
